SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TablaPeriodo](
	[ID_Periodo] [tinyint] NOT NULL,
	[Mes] [nvarchar](50) NOT NULL,
	[Año] [smallint] NOT NULL,
 CONSTRAINT [PK_Tabla_Periodo] PRIMARY KEY CLUSTERED 
(
	[ID_Periodo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
